### PR TITLE
Update FAKIconImage.ios.js

### PR DESCRIPTION
**Pull request by auser**
Fixes a few changes for React 0.4.3

### CODE REVIEW

**Comment by ptmt** [comment]
+1

**Comment by ptmt** [comment]
Also, the same renames needed in `SMXTabBarIconItemIOS` and `SMXTabBarIOS`

**Comment by christopherdro** [comment]
Just a suggestion to change the var names as well to keep things consistent. 

This would require another small change on line 101.

**Comment by corymsmith** [comment]
I'll make this additional changes and merge this in shortly

**Comment by corymsmith** [comment]
All merged in and published version 0.0.7

**Pull request merged**
