### PR TITLE
Support changed method names of react-native >=0.10.0

### PR DESCRIPTION
**Pull request by michaelcontento**
See https://github.com/facebook/react-native/commit/1fb26d43191059fef3a4aacdf6385912b12e419f#diff-3e154f92c7ba4cb47e96785b9dadf3aa

### CODE REVIEW

**Comment by jdmunro** [comment]
Do you need to also change the React Native dependency in the example project? I made these same changes in my own fork and I have encountered issues with the `onPress()` method of `TabBarItemIOS` not being called when you tap the icons.

https://github.com/jdmunro/react-native-icons/tree/react-0.10.0-rc-support

**Comment by alinz** [comment]
:+1:

**Comment by michaelcontento** [comment]
@jdmunro : You're right, with this PR you need to use `react-native >= 0.10.x`. I've also updated the `package.json` in the example folder. 

Another addition with this PR is the `devDependency` record in the root `package.json` ([click for details](https://github.com/michaelcontento/react-native-icons/commit/7f73cdace2082cb8e1d4ca96a34f50e1e36b33a5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R19))!

**Comment by jdmunro** [comment]
@michaelcontento No worries. Did you encounter the issue where the tab bar buttons simply don't work with 0.10.0-rc in the example project?

**Comment by michaelcontento** [comment]
No, I'm currently only using `<Icon>` in my app :|

**Comment by jsierles** [comment]
There are still two issues related to the tab bar. Looking into it.

**Comment by mfkp** [comment]
@jdmunro my tab bar buttons no longer work after upgrading to 0.10.0-rc

**Comment by corymsmith** [comment]
I'm currently on vacation with limited access to internet so haven't had a chance to take a look at this yet.

**Comment by zachguo** [comment]
Using this fork, it successfully builds but tab bar icons no longer respond to tap.

**Comment by corymsmith** [comment]
I've sorted out why the tab bar buttons don't work, the event name in RN changed from "topTap" to "press". I've implemented this in https://github.com/corymsmith/react-native-icons/tree/support-for-0.10.0-rc. Once 0.10.0 is released I'll merge that branch in and publish.

@jsierles What other issues did you run into? Just want to make sure I have everything sorted.

**Comment by jsierles** [comment]
Looks good to me!

**Comment by JedWatson** [comment]
@corymsmith react-native@0.10.0 is out :)

I can confirm building in Xcode completely breaks using the `0.3.4` release with RN .10 but everything seems to work correctly when you use the `support-for-0.10.0-rc` branch.

**Comment by corymsmith** [comment]
Sounds good, I'll merge in and publish a new version in a couple hours :)

**Comment by JedWatson** [comment]
Awesome, thanks!

**Comment by corymsmith** [comment]
@jedwatson I'm actually out in your part of the world, currently in Brisbane for a few days then heading south

**Comment by JedWatson** [comment]
@corysmith awesome! Just found you on Twitter, I'll ping you on there. Looks like you two are having a great time - If you're coming to Sydney would love to meet up :)

**Comment by corymsmith** [comment]
Just merged in my support branch and published 0.3.6 to NPM

**Pull request closed without merging**
