### PR TITLE
Add selectedImage to TabBarItemIOS

### LINKED ISSUE #90: TabBarItemIOS iconName not responding to updates (at all)
I tried to switch the icon when the user enters/leaves a TabBarItem. Ion provides both filled and outlined versions of iOS icons, so I was trying the following:

``` js
_iconHelper(tab, icon) {
  if (this.state.selectedTab === tab) return icon;
  return icon + '-outline';
}
```

And instead of a static string on iconName, I use something like `iconName={this._iconHelper('tabName', 'ion|ios-pie')}`. The problem is, it only works with the tab that was initially selected. If I switch tabs, its icon changes to the outlined version; if I select it again, it returns to the filled version. But it doesn't work on the other tabs, they stay outlined all the time. I put a console.log to verify if the helper function was being called, and it is working perfectly, but the other icons doesn't change at all...

### PR DESCRIPTION
**Pull request by jose-cieni-afterverse**
Fixes #90.

This PR adds the ability to provide a different icon when a tab is selected.
Example:

``` js
<TabBarIOS.Item
  name={'dashboard'}
  iconName='ion|ios-pie-outline'
  selectedIconName='ion|ios-pie'
  title='Dashboard'
  iconSize={32} // optionally provide a selectedIconSize
  selected={this._isSelected('dashboard')}
  onPress={() => this._setTab('dashboard')}>
  {this._renderDashboardContent()}
</TabBarIOS.Item>
```

### CODE REVIEW

**Comment by corymsmith** [comment]
Thanks for this José, I'll publish a new version so NPM today / tomorrow with this and a few other updates

**Comment by jose-cieni-afterverse** [comment]
@corymsmith thanks!

**Comment by corymsmith** [comment]
@jose-cieni-movile Just published this to NPM with version 0.4.0. Thanks alot for this PR!

**Comment by cienijr** [comment]
@corymsmith I'm opening a new PR to add some examples :smile:

**Pull request merged**
